Name = input('Hello! What is your name?')
print('Hi,', Name)
Height = input('What is your height?')
Weight = input('what is your weight?')
print('So, you are', Height, 'cm and', Weight, 'kg.')
print(f"So, you are {Height} cm and {Weight} kg")
Age = int(input('How old are you?')) 
print(f"So you are born in Year of {2025 - Age}")
print('See you later,', Name)